#!/usr/bin/env groovy

node {
    stage 'Git checkout'
    echo 'Checking out git repository'
    git url: 'https://github.com/jamesfalkner/coolstore-microservice'

    stage 'Build catalog-service with maven'
    echo 'Building project'
    def mvnHome = tool 'M3'
    def javaHome = tool 'jdk8'

    stage 'Build image and deploy in Dev'
    echo 'Building docker image and deploying to Dev'
    buildProject(env.PROD_PROJECT + '-dev')

    stage 'Automated tests'
    echo 'This stage simulates automated tests'
    sh "${mvnHome}/bin/mvn -f catalog-service -B -Dmaven.test.failure.ignore clean package verify"

    stage 'Deploy to QA'
    echo 'Deploying to QA'
    deployProject(env.PROD_PROJECT + '-dev', env.PROD_PROJECT + '-qa', true)

    stage 'Wait for approval'
    input 'Approve to production?'

    stage 'Deploy to production'
    echo 'Deploying to production'
    deployProject(env.PROD_PROJECT + '-dev', env.PROD_PROJECT, false)
}

def prereqs(String project) {
    projectSet(project)

    // build catalog service and wait for it to finish
    sh "oc create -f openshift-templates/secrets/coolstore-secrets.json || echo 'Secrets and serviceaccount already created'"
    sh "oc policy add-role-to-user view system:serviceaccount:${project}:default -n ${project}"
    sh "oc policy add-role-to-user view system:serviceaccount:${project}:sso-service-account -n ${project}"

}

// Creates a Build and triggers it
def buildProject(String project){
    prereqs(project)
    sh "oc new-app --file=openshift-templates/catalog-service.json -p MAVEN_MIRROR_URL='${env.MAVEN_MIRROR_URL ? env.MAVEN_MIRROR_URL : ""}' || oc start-build catalog-service"
    sh "oc expose service catalog-service || echo 'Service already exposed'"
    sh "oc logs -f bc/catalog-service"
}

// Tag the ImageStream from an original project to force a deployment
def deployProject(String origProject, String project, boolean expose){
    prereqs(project)
    sh "oc policy add-role-to-user system:image-puller system:serviceaccount:${project}:default -n ${origProject}"
    sh "oc policy add-role-to-group system:image-puller system:serviceaccounts:${project} -n ${origProject}"

    sh "oc tag ${origProject}/catalog-service:latest ${project}/catalog-service:latest"
    sh "oc new-app --image-stream=catalog-service -l application=catalog-service || echo 'Application exists'"

    if (expose) {
        sh "oc expose service catalog-service || echo 'Service already exposed'"
    }

}

// Login and set the project
def projectSet(String project){
    //Use a credential called openshift-dev
    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'openshift-dev', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
        sh "oc login --insecure-skip-tls-verify=true -u $env.USERNAME -p $env.PASSWORD https://kubernetes.default.svc.cluster.local"
    }
    sh "oc new-project ${project} || echo 'Project exists'"
    sh "oc project ${project}"
}

